apiVersion: v1
kind: Pod
metadata:
  name: client
spec:
  volumes:
  - name: mr-fs
    persistentVolumeClaim:
      claimName: mr-fs
  - name: fileserver-sm
    persistentVolumeClaim:
      claimName: fileserver-sm
  containers:
    - name: ubuntu
      image: ubuntu:latest
      command: ["/bin/sleep", "3650d"]
      imagePullPolicy: IfNotPresent
      env:
      - name: MASTERS_SERVICE_URI
        value: "mapreduce-taskmanager-service:5042"
      - name: STORAGE_DIR
        value: "/mnt/mr-fs"
      volumeMounts:
      - name: mr-fs
        mountPath: /mnt/mr-fs/
      - name: fileserver-sm
        mountPath: /mnt/backup/
      resources:
        limits:
          cpu: 800m
          ephemeral-storage: 5Gi
          memory: 2Gi
        requests:
          cpu: 800m
          ephemeral-storage: 5Gi
          memory: 2Gi
