apiVersion: apps/v1
kind: Deployment
metadata:
  name: mapreduce-taskmanager
  labels:
    app: mapreduce-taskmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mapreduce-taskmanager
  template:
    metadata:
      labels:
        app: mapreduce-taskmanager
    spec:
      volumes:
      - name: mr-fs
        persistentVolumeClaim:
          claimName: mr-fs
      containers:
      - name: mapreduce-taskmanager
        image: us-central1-docker.pkg.dev/mapreduce-42/mapreduce/taskmanager:latest
        imagePullPolicy: Always
        env:
        - name: WORKERS_SERVICE_URI
          value: "mapreduce-worker-service:5045"
        - name: STORAGE_DIR
          value: "/mnt/mr-fs"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - containerPort: 5044
        volumeMounts:
        - name: mr-fs
          mountPath: /mnt/mr-fs/
        resources:
          limits:
            cpu: 1000m
            ephemeral-storage: 512Mi
            memory: 1Gi
          requests:
            cpu: 1000m
            ephemeral-storage: 512Mi
            memory: 1Gi
